
name: app_environment
channels:
  - snowflake
dependencies:
  - snowflake=*
  - snowflake-ml-python=*
  - snowflake-snowpark-python=*
  - snowflake=*
  - snowflake-ml-python=*
  - snowflake-snowpark-python=*
  - snowflake.core=*
  - trulens-connectors-snowflake=*
  - langchain-core
  - langchain-text-splitters
  - pypdf
  - pip
  - pip:
      - langchain_community
      

  
  